"""Add cascade delete to user images

Revision ID: 7a23a05162ba
Revises: 127414460a17
Create Date: 2025-11-17 15:07:10.290040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a23a05162ba'
down_revision = '127414460a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_image_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_image_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
